name: ci

on:
    push:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3
            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-lint-${{ hashFiles('**/package-lock.json') }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install node_modules
              run: >
                  npm ci
            - name: ESLint
              run: >
                  npm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3
            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-test-${{ hashFiles('**/package-lock.json') }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install node_modules
              run: >
                  npm ci
            - name: Jest
              run: >
                  npm run test
