name: Release

on:
    release:
        types: ["created"]
    push:

jobs:
    ci:
        uses: "./.github/workflows/ci.yml"
        secrets: inherit

    build-release:
        runs-on: "ubuntu-latest"
        needs: ["ci"]
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            - name: install and build
              run: npm ci && npm run build

            - name: publish
              run: |
                  if [ "${{ github.event_name }}" == "release" ]; then
                    # This is a release, publish without a tag
                    npm publish --provenance --access public
                  else
                    branch="${{ github.ref_name }}"
                    tmp=$(mktemp)
                    short_sha=$(echo "${{ github.sha }}" | cut -c 1-7)

                    jq --arg x "-$short_sha" '.version += $x' package.json > "$tmp" && mv "$tmp" package.json

                    if [ "$branch" != "master" ]; then
                      # This is not the master branch, publish with the branch name as a tag
                      npm publish --provenance --access public --tag "$branch"
                    fi
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
